name: Deploy Schedule

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy schedule.html
      run: |
        # Add your deployment commands here
        # For example, if you are using GitHub Pages:
        echo "schedule.html" > index.html
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add index.html
        git commit -m 'Deploy schedule.html'
        git push origin main
